import ProjectDescription

let workspace = Workspace(
  name: "SeeYouAgain",
  projects: [
    "Projects/App",
    "Projects/Core",
    "Projects/DesignSystem",
    "Projects/Features/Scene",
    "Projects/Features/Coordinator",
  ],
  schemes: [
    Scheme(
      name: "Prod-SeeYouAgain",
      buildAction: .buildAction(targets: [.project(path: "Projects/App", target: "Prod-SeeYouAgain")]),
      runAction: .runAction(configuration: .release),
      archiveAction: .archiveAction(configuration: .release),
      profileAction: .profileAction(configuration: .release),
      analyzeAction: .analyzeAction(configuration: .release)
    ),
    Scheme(
      name: "Dev-SeeYouAgain",
      buildAction: .buildAction(targets: [.project(path: "Projects/App", target: "Dev-SeeYouAgain")]),
      runAction: .runAction(configuration: .debug),
      archiveAction: .archiveAction(configuration: .debug),
      profileAction: .profileAction(configuration: .debug),
      analyzeAction: .analyzeAction(configuration: .debug)
    ),
  ],
  generationOptions: .options(autogeneratedWorkspaceSchemes: .disabled)
)
